name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release V${{ github.run_id }} (${{ github.event.head_commit.message }})
          tag_name: Commit_${{ github.sha }}
          files: cv.pdf
